START : '2020-01-01'  # global start date for all fetches
DEBUG : True
params : {  'from': START, 
            'to': today,
            'api_token': EOD_API    }
url : f'https://eodhd.com/api/eod/'
MAX_AGE : 24
today : time.strftime("%Y-%m-%d")
